
plugins {
    id "org.sonarqube" version "3.0"
}

apply plugin: 'com.android.application'

android {

    buildFeatures {
        buildConfig true
    }
    lint {
        checkReleaseBuilds false
    }
    namespace 'es.gob.afirma'
    compileSdk 36
    defaultConfig {
        applicationId "es.gob.afirma"
        minSdkVersion 23
        targetSdkVersion 36
        multiDexEnabled true
        versionCode 28
        versionName "1.9.1"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        targetCompatibility 17
        sourceCompatibility 17
    }
    packagingOptions {
        resources {
            pickFirsts += ['ACRAIZ-SHA2.crt']
            excludes += "META-INF/versions/9/OSGI-INF/MANIFEST.MF"
        }
    }


    // Los otros proyectos de Afirma tienen dependencias que entran en conflicto
    // con las clases de Android, silenciamos los errores hasta que se arreglen

    sourceSets.main.java.filter.exclude 'com/**/package-info.*'
}

repositories {
    mavenLocal()
    google()
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

	implementation 'com.google.android.material:material:1.12.0'

    implementation ('es.gob.afirma.jmulticard:jmulticard-android:2.0') {
        exclude(module: 'support-v4')
        exclude(module: 'android')
    }
    implementation 'es.gob.afirma.jmulticard:jmulticard-jse:2.0'

    implementation('es.gob.afirma:afirma-crypto-pdf:1.10-SNAPSHOT') {
        exclude(module: 'afirma-lib-itext')
    }
    implementation 'es.gob.afirma.lib:afirma-lib-itext-android:1.6'
    implementation 'es.gob.afirma:afirma-core:1.10-SNAPSHOT'
    implementation ('es.gob.afirma:afirma-core-keystores:1.10-SNAPSHOT') {
        exclude(group: 'es.gob.afirma.jmulticard')
    }
    implementation 'es.gob.afirma:afirma-crypto-cades:1.10-SNAPSHOT'
    implementation 'es.gob.afirma:afirma-crypto-cadestri-client:1.10-SNAPSHOT'
    implementation 'es.gob.afirma:afirma-crypto-xadestri-client:1.10-SNAPSHOT'
    implementation 'es.gob.afirma:afirma-crypto-padestri-client:1.10-SNAPSHOT'
    implementation 'es.gob.afirma:afirma-crypto-cades-multi:1.10-SNAPSHOT'
    implementation 'es.gob.afirma:afirma-crypto-core-pkcs7:1.10-SNAPSHOT'
    implementation 'es.gob.afirma:afirma-crypto-core-pkcs7-tsp:1.10-SNAPSHOT'
    implementation 'com.google.code.gson:gson:2.10'

    implementation 'com.github.mhiew:android-pdf-viewer:3.2.0-beta.3'

    // Java language implementation
    implementation "androidx.fragment:fragment:1.8.6"


    // Restricciones para evitar clases duplicadas debido a dependencias
    constraints {
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.0") {
            because("kotlin-stdlib-jdk7 is now a part of kotlin-stdlib")
        }
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.0") {
            because("kotlin-stdlib-jdk8 is now a part of kotlin-stdlib")
        }
    }
}
